/**
 * Device and agent-credential lifecycle commands (task 8.1).
 *
 * Covers device create / disable / re-enable and credential rotate / revoke.
 * Each command is a sensitive inventory operation gated by the pure permission
 * matrix (task 5.1, `manage_inventory`), re-checks the permission itself
 * (defense-in-depth), operates only within the caller's tenant scope (task 7.1
 * — a cross-tenant target is indistinguishable from a missing one), and writes
 * a complete audit event in the same transaction as the mutation (task 5.7,
 * requirement 19.1). Device type is validated against the full contract enum
 * (`simulator|android|modem|goip|api`) but only `simulator` is activated for
 * the MVP flow via the pure `decideDeviceCreation` policy (task 5.7,
 * requirement 17.1). Capabilities are declared explicitly (task 5.7,
 * requirement 21.4).
 *
 * The 256-bit agent secret is generated by the injected credential factory,
 * shown to the caller exactly once (requirement 5.2), and only its peppered,
 * per-device-salted SHA-256 hash is persisted. Rotation and revocation
 * immediately invalidate the previous hash — the MVP grace period is zero
 * (design section 6; requirement 5.5). Every outcome is a tagged union so the
 * transport layer maps results to safe responses without relying on thrown
 * control flow.
 */
import { createAuditEvent, type AuditEventDescriptor } from "@domain/task-5-7";
import {
  declareCapabilities,
  decideDeviceCreation,
  isDeviceType,
  type DeviceType,
} from "@domain/task-5-7";
import { Task57DomainError } from "@domain/task-5-7";

import { checkPermission, type SessionContext } from "../authorization/session-context";
import type {
  Clock,
  DeviceCredentialFactory,
  DeviceManagementGateway,
  DeviceManagementTransaction,
  DeviceView,
  IdGenerator,
} from "./ports";

/** Maximum device label length (matches the `VarChar(120)` column). */
const MAX_LABEL_LENGTH = 120;

/** A one-time agent credential returned to the caller on create/rotate. */
export interface OneTimeAgentCredential {
  readonly credentialId: string;
  readonly publicId: string;
  /**
   * The full agent token for `Authorization: Device <token>`, i.e.
   * `<publicId>.<secret>`. Shown exactly once; never persisted or logged.
   */
  readonly agentToken: string;
}

export interface CreateDeviceInput {
  readonly caller: SessionContext;
  readonly type: string;
  readonly label: string;
  readonly capabilities: {
    readonly sms: boolean;
    readonly notification: boolean;
    readonly resend: boolean;
    readonly operator?: string | null;
    readonly slots: number;
  };
  /** Request identity for the audit trail (uuid). */
  readonly requestId: string;
}

export interface DeviceIdInput {
  readonly caller: SessionContext;
  readonly deviceId: string;
  readonly requestId: string;
}

export interface DisableDeviceInput extends DeviceIdInput {
  readonly reason?: string;
}

export type DeviceCommandOutcome =
  | { readonly ok: true; readonly device: DeviceView; readonly credential?: OneTimeAgentCredential }
  | { readonly ok: false; readonly reason: "forbidden" }
  | { readonly ok: false; readonly reason: "not_found" }
  | { readonly ok: false; readonly reason: "partner_not_approved" }
  | { readonly ok: false; readonly reason: "simulator_not_allowed" }
  | { readonly ok: false; readonly reason: "validation"; readonly code: string };

export interface DeviceManagementServiceDeps {
  readonly gateway: DeviceManagementGateway;
  readonly credentialFactory: DeviceCredentialFactory;
  readonly clock: Clock;
  readonly idGenerator: IdGenerator;
  /** Runtime environment; simulator creation is gated by it (task 5.7). */
  readonly environment: string;
}

export class DeviceManagementService {
  private readonly deps: DeviceManagementServiceDeps;

  constructor(deps: DeviceManagementServiceDeps) {
    this.deps = deps;
  }

  /**
   * Register a device for the caller's tenant and issue its first agent
   * credential. Only an approved partner may register devices (requirement
   * 5.1); simulator devices additionally pass the environment/allowlist policy
   * (requirement 17.1). The 256-bit secret is returned once.
   */
  async createDevice(input: CreateDeviceInput): Promise<DeviceCommandOutcome> {
    const denied = this.requireManageInventory(input.caller);
    if (denied) return denied;

    if (!isDeviceType(input.type)) {
      return { ok: false, reason: "validation", code: "INVALID_DEVICE_TYPE" };
    }
    const type: DeviceType = input.type;

    if (
      typeof input.label !== "string" ||
      input.label.trim().length === 0 ||
      input.label.length > MAX_LABEL_LENGTH
    ) {
      return { ok: false, reason: "validation", code: "INVALID_LABEL" };
    }

    let capabilities;
    try {
      capabilities = declareCapabilities(input.capabilities);
    } catch (error) {
      return { ok: false, reason: "validation", code: capabilityErrorCode(error) };
    }

    return this.deps.gateway.runInTenant(input.caller.tenant, async (tx) => {
      const partner = await tx.loadPartnerGate();
      if (partner === null) return { ok: false, reason: "not_found" } as const;
      if (partner.status !== "approved") {
        return { ok: false, reason: "partner_not_approved" } as const;
      }

      const decision = decideDeviceCreation(type, {
        environment: this.deps.environment,
        partnerSimulatorAllowed: partner.simulatorAllowed,
      });
      if (!decision.allowed) {
        return { ok: false, reason: "simulator_not_allowed" } as const;
      }

      const now = this.deps.clock.nowEpochMs();
      const deviceId = this.deps.idGenerator.uuid();
      const device = await tx.createDevice({
        id: deviceId,
        type,
        label: input.label,
        capabilities,
        createdAtEpochMs: now,
      });

      const issued = this.deps.credentialFactory.issue(deviceId);
      const credentialId = this.deps.idGenerator.uuid();
      await tx.createCredential({
        id: credentialId,
        deviceId,
        publicId: issued.publicId,
        secretHash: issued.secretHash,
        createdAtEpochMs: now,
      });

      await this.writeAudit(tx, {
        caller: input.caller,
        requestId: input.requestId,
        descriptor: createAuditEvent({
          actorType: "partner_member",
          actorRef: input.caller.principal.memberId,
          action: "device.changed",
          targetType: "partner_device",
          targetId: deviceId,
          result: "success",
          occurredAtEpochMs: now,
          metadata: { change: "created", type, capabilities },
        }),
      });
      await this.writeAudit(tx, {
        caller: input.caller,
        requestId: input.requestId,
        descriptor: createAuditEvent({
          actorType: "partner_member",
          actorRef: input.caller.principal.memberId,
          action: "credential.changed",
          targetType: "device_credential",
          targetId: credentialId,
          result: "success",
          occurredAtEpochMs: now,
          // The publicId is not secret; the secret itself is never audited.
          metadata: { change: "issued", deviceId, publicId: issued.publicId },
          sensitiveValues: [issued.secret],
        }),
      });

      return {
        ok: true,
        device,
        credential: {
          credentialId,
          publicId: issued.publicId,
          agentToken: `${issued.publicId}.${issued.secret}`,
        },
      } as const;
    });
  }

  /**
   * Disable a device. A disabled device is fail-closed: the Agent API rejects
   * all of its operations (requirement 5.6). Idempotent-friendly — disabling an
   * already-disabled device simply re-stamps `disabledAt`.
   */
  async disableDevice(input: DisableDeviceInput): Promise<DeviceCommandOutcome> {
    const denied = this.requireManageInventory(input.caller);
    if (denied) return denied;

    return this.deps.gateway.runInTenant(input.caller.tenant, async (tx) => {
      const existing = await tx.findDeviceById(input.deviceId);
      if (existing === null) return { ok: false, reason: "not_found" } as const;

      const now = this.deps.clock.nowEpochMs();
      const device = await tx.updateDeviceStatus(input.deviceId, {
        effectiveStatus: "disabled",
        disabledAtEpochMs: now,
      });

      await this.writeAudit(tx, {
        caller: input.caller,
        requestId: input.requestId,
        descriptor: createAuditEvent({
          actorType: "partner_member",
          actorRef: input.caller.principal.memberId,
          action: "device.changed",
          targetType: "partner_device",
          targetId: device.id,
          result: "success",
          occurredAtEpochMs: now,
          metadata: {
            change: "disabled",
            previousStatus: existing.effectiveStatus,
            nextStatus: device.effectiveStatus,
            ...(input.reason ? { reason: input.reason } : {}),
          },
        }),
      });

      return { ok: true, device } as const;
    });
  }

  /**
   * Re-enable a disabled device. The device returns to `offline` and must send
   * a fresh heartbeat before it can serve inventory again (design section 9).
   */
  async reEnableDevice(input: DeviceIdInput): Promise<DeviceCommandOutcome> {
    const denied = this.requireManageInventory(input.caller);
    if (denied) return denied;

    return this.deps.gateway.runInTenant(input.caller.tenant, async (tx) => {
      const existing = await tx.findDeviceById(input.deviceId);
      if (existing === null) return { ok: false, reason: "not_found" } as const;

      const now = this.deps.clock.nowEpochMs();
      const device = await tx.updateDeviceStatus(input.deviceId, {
        effectiveStatus: "offline",
        disabledAtEpochMs: null,
      });

      await this.writeAudit(tx, {
        caller: input.caller,
        requestId: input.requestId,
        descriptor: createAuditEvent({
          actorType: "partner_member",
          actorRef: input.caller.principal.memberId,
          action: "device.changed",
          targetType: "partner_device",
          targetId: device.id,
          result: "success",
          occurredAtEpochMs: now,
          metadata: {
            change: "re_enabled",
            previousStatus: existing.effectiveStatus,
            nextStatus: device.effectiveStatus,
          },
        }),
      });

      return { ok: true, device } as const;
    });
  }

  /**
   * Rotate a device's agent credential. Every currently-active credential is
   * revoked immediately (grace period zero on the MVP) and a new 256-bit secret
   * is issued and returned once (requirement 5.5, 5.2).
   */
  async rotateCredential(input: DeviceIdInput): Promise<DeviceCommandOutcome> {
    const denied = this.requireManageInventory(input.caller);
    if (denied) return denied;

    return this.deps.gateway.runInTenant(input.caller.tenant, async (tx) => {
      const existing = await tx.findDeviceById(input.deviceId);
      if (existing === null) return { ok: false, reason: "not_found" } as const;

      const now = this.deps.clock.nowEpochMs();
      const revokedCount = await tx.revokeActiveCredentials(input.deviceId, now);

      const issued = this.deps.credentialFactory.issue(input.deviceId);
      const credentialId = this.deps.idGenerator.uuid();
      await tx.createCredential({
        id: credentialId,
        deviceId: input.deviceId,
        publicId: issued.publicId,
        secretHash: issued.secretHash,
        createdAtEpochMs: now,
      });

      await this.writeAudit(tx, {
        caller: input.caller,
        requestId: input.requestId,
        descriptor: createAuditEvent({
          actorType: "partner_member",
          actorRef: input.caller.principal.memberId,
          action: "credential.changed",
          targetType: "device_credential",
          targetId: credentialId,
          result: "success",
          occurredAtEpochMs: now,
          metadata: {
            change: "rotated",
            deviceId: input.deviceId,
            publicId: issued.publicId,
            revokedCount,
          },
          sensitiveValues: [issued.secret],
        }),
      });

      return {
        ok: true,
        device: existing,
        credential: {
          credentialId,
          publicId: issued.publicId,
          agentToken: `${issued.publicId}.${issued.secret}`,
        },
      } as const;
    });
  }

  /**
   * Revoke a device's active credentials without issuing a replacement. The old
   * hashes are rejected by the Agent API immediately (requirement 5.5).
   */
  async revokeCredential(input: DeviceIdInput): Promise<DeviceCommandOutcome> {
    const denied = this.requireManageInventory(input.caller);
    if (denied) return denied;

    return this.deps.gateway.runInTenant(input.caller.tenant, async (tx) => {
      const existing = await tx.findDeviceById(input.deviceId);
      if (existing === null) return { ok: false, reason: "not_found" } as const;

      const now = this.deps.clock.nowEpochMs();
      const revokedCount = await tx.revokeActiveCredentials(input.deviceId, now);

      await this.writeAudit(tx, {
        caller: input.caller,
        requestId: input.requestId,
        descriptor: createAuditEvent({
          actorType: "partner_member",
          actorRef: input.caller.principal.memberId,
          action: "credential.changed",
          targetType: "partner_device",
          targetId: input.deviceId,
          result: "success",
          occurredAtEpochMs: now,
          metadata: { change: "revoked", deviceId: input.deviceId, revokedCount },
        }),
      });

      return { ok: true, device: existing } as const;
    });
  }

  /** `manage_inventory` gate shared by every device command (requirement 4.4). */
  private requireManageInventory(
    caller: SessionContext,
  ): { readonly ok: false; readonly reason: "forbidden" } | null {
    const permission = checkPermission(caller, "manage_inventory");
    return permission.allowed ? null : { ok: false, reason: "forbidden" };
  }

  private async writeAudit(
    tx: DeviceManagementTransaction,
    args: {
      readonly caller: SessionContext;
      readonly requestId: string;
      readonly descriptor: AuditEventDescriptor;
    },
  ): Promise<void> {
    await tx.recordAudit({
      id: this.deps.idGenerator.uuid(),
      partnerId: args.caller.tenant.partnerId,
      requestId: args.requestId,
      descriptor: args.descriptor,
    });
  }
}

/** Map a capability declaration failure onto a stable validation code. */
function capabilityErrorCode(error: unknown): string {
  return error instanceof Task57DomainError ? error.code : "INVALID_CAPABILITY";
}
